### ISSUE TITLE
Ability to colorize favicons

### ISSUE THREAD

**Issue by ssbarnea** [sylouuu/chrome-tab-modifier#58]
We all know that Chrome does not allow us to colorize tabs but because we can customize favicons it means that we can also colorize them. 

Have a look at the screenshot below which contains 3 tabs from 3 different Jenkins instances, all of them having the same favicon. 

![new issue sylouuuchrome-tab-modifier 2017-01-24 08-48-33](https://cloud.githubusercontent.com/assets/102495/22240196/ea3c39dc-e211-11e6-9c6f-e3e4dff75550.png)

Changing favicons yourself and hosting them somewhere online is a very time consuming operations so it would be much easier if this extension would allow us to apply a recoloring filter on the original favicon of the site. This would allow us to distinguish between different similar software instances.

The favicon is supposed to be saved locally at the configuration time and filtered, no refresh is necessary.

**Comment by sylouuu** [comment]
Hi @ssbarnea,

I understand what you need. However this is too much work and I want to keep this extension easier to use, easier to maintain.

Best

**Comment by xkrt** [comment]
@sylouuu it will be very useful to have that feature. I found your extension exactly for the purpose that you described at [Why](https://github.com/sylouuu/chrome-tab-modifier#why), but I use pinned tabs, so change of title doesn't help me much. It will be super useful if your extension will change background color of favicon based on rule, for example blue for DEV, yellow for PREPROD, etc.

**Comment by ssbarnea** [comment]
@sylouuu Thanks. You described perfectly the need to find a way to apply some filters to original favicon. I don't really care about which filter would be used.

This reminds of how I addressed the tab issues in iTerm: I created a transparent ssh function that does colorize the tab based on a hash of the machine IP. This means that each each SSH session will have a colour that stays with it.

**Comment by sylouuu** [comment]
@xkrt Sure useful but consuming too much time because I'm not familiar with drawing images on-the-fly.

You still have alternatives:

* Use a local image: https://github.com/sylouuu/chrome-tab-modifier#local-files-file
* Use an external image (absolute url)
* Use a Data-URI format
* Use a pre-defined colored icon: it must be the best alternative if you are working on only one project

Otherwise, unpin the tabs you are working on.

Best

**Comment by xkrt** [comment]
@sylouuu thanks for the advice. I take favicon, put color spot on it and make rule with data-uri, works for me.
